# Generated by Django 6.0.2 on 2026-02-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Воротар'), ('DF', 'Захисник'), ('MF', 'Півзахисник'), ('FW', 'Нападник')], default='GK', max_length=2),
        ),
    ]
