# Generated by Django 6.0.2 on 2026-02-20 13:56

import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[teams.models.validate_age]),
        ),
    ]
