# Generated by Django 6.0.2 on 2026-02-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_match_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Голи гостьової команди'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Голи домашньої команди'),
        ),
    ]
